### ISSUE TITLE
----

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#100]
https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/methods/source_full_code_test/source-fullcodetest.md

**Comment by atherdon** [comment]
@Bogdan060895 нужно перенести этот файл. в какой то момент попробуем пройти по файлу с полным контентом и посмотреть на результат.
только незнаю куда именно его закинуть.
внутрь **src** нехочу, потому что содержимое этой папки выкладывается, когда модуль пакуется и собирается.
внутрь tests - неуверен, потому что у нас может возникнуть непонимание - к какому именно тесту это файл относится.

отдаю это решение на откуп вам

**Comment by Bogdan060895** [comment]
В таком случае, для него можно пока создать отдельную директорию, рядом с src и tests? Как насчет такого варианта?

**Comment by atherdon** [comment]
пока незнаю. давайте так, а потом подумаем.

проблема в чем:

- сейчас мы шаг за шагом идем к тому, чтобы покрыть небольшими тестами наши константы.
но проблема в том, что основной модуль требует большего количества тестов.
например как те файлы, которые вы переносили в этот модуль. 

поэтому в данный момент есть заковыка, которую мы еще не придумали как решить.

плюс мы ждем когда мой друг DevOps вернется в харьков и настроит для всех мелких модулей удобный coding workflow... возможно он и подскажет правильный вариант

**Comment by Bogdan060895** [comment]
Тогда это я сделал

**Comment by atherdon** [comment]
неуверен...

опишу в PR

**Comment by Bogdan060895** [comment]
Перекинул его пока, просто, в общий список файлов, без отдельной директории

**Comment by atherdon** [comment]
ок, пусть пока так будет
