### ISSUE TITLE
---

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#101]
https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/typography/h1-at-first-line/index.js

**Comment by atherdon** [comment]
@Bogdan060895 нам нужно скопировать первые 2 строки из этого файла и вставить их в самом начале в файлах tests.js*, чтобы мы потом могли подключать файлы content.md

**Comment by Bogdan060895** [comment]
Насколько я понял, имеются ввиду все файлы в папках с расширением .js ?

**Comment by atherdon** [comment]
> Насколько я понял, имеются ввиду все файлы в папках с расширением .js ?

да

**Comment by Bogdan060895** [comment]
Тогда, готово тоже

**Comment by atherdon** [comment]
написал комментарий в #107

**Comment by atherdon** [comment]
закрою когда сделаем
