### ISSUE TITLE
comment 2nd and 3rd test statement for now

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#105]
вначале мы будем добавлять только 1й тест, поэтому остальные нам пока не нужны. мы их скроем, и когда надо будет - мы их вернем обратно

чтобы добавить комментарий к строке - вначале ставится `//`

**Comment by atherdon** [comment]
нужно скрыть пока 2й и 3й test чтобы я мог настроить jest и чтобы он не ругался

**Comment by atherdon** [comment]
добавить `//` вначале каждой строки

**Comment by Bogdan060895** [comment]
сделал
