### ISSUE TITLE
первые уроки по jest

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#106]
я неуверен нужно ли нам устанавливать все, как они предлагают - но ознакомится не помешает.
тк модуль уже настроен - некотороые шаги пропускаются(или можете параллельно создать себе пустой проджект)

https://www.youtube.com/watch?v=f4aedP8dLDI

https://www.youtube.com/watch?v=IEDe8jl5efU

https://www.youtube.com/watch?v=yLRVDM3_4_M

**Comment by atherdon** [comment]
жаль конечно что это русские...
но пока что рано туториалы на английском мне кажется

**Comment by atherdon** [comment]
https://www.youtube.com/watch?v=MDjj1k9JhVU

**Comment by atherdon** [comment]
https://www.youtube.com/watch?v=GHVvrYD4VRE

**Comment by Bogdan060895** [comment]
Начал
