### ISSUE TITLE
у нас пропало расширение *.test.js

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#115]
открыл код из основного репозитория, у нас файлы называются как `blockquote.js` а не `blockquote.test.js`

**Comment by atherdon** [comment]
нужно сделать sync, я обновляю тесты сейчас

**Comment by Bogdan060895** [comment]
Так нужно сделать со всеми файлами .js ? прописать везде " test" ?

**Comment by atherdon** [comment]
Только с файлами из папки test/* и делайте sync всегда, потому что я сейчас
тоже работаю в этом репозитории

вс, 5 июн. 2022 г., 7:32 PM Bogdan060895 ***@***.***>:

**Comment by atherdon** [comment]
completed
