### ISSUE TITLE
review all content.md files inside of tests folder

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#145]
пару месяцев назад мы начали переносить файлы с контентом, которые мы будем использовать для наших тестов.

но я непомню, всю ли работу мы сделали.
можете вначале просто пройтись по всем папкам внутри `tests`, открыть каждый файл content.md и посмотреть что там внутри.

если мы чтото недоделали, поидее вы заметите

**Comment by atherdon** [comment]
### testing content will be here


такой текст означает что мы не все перенесли

**Comment by atherdon** [comment]
результатом выполненой задачи будет список папок/файлов в которые контент мы не перенесли.

потом я покажу вам в каком месте хранятся эти файлы и вы их перенесете

**Comment by atherdon** [comment]
- q
- ulList

**Comment by Olgalex** [comment]
- block quote /
- link /Changed files/
- strong /Changed files/
- ul-list /updates/

**Comment by Olgalex** [comment]
blockquote - may it should be enough? (> this is blockquote)
link - just for remind to follow about ways
strong - it seems just comment, not test
ul-list - there were previous tests, not new

**Comment by Olgalex** [comment]
code 
del
I'm not sure if all information there

**Comment by atherdon** [comment]
> blockquote - may it should be enough? (> this is blockquote) 

this one is fine

**Comment by atherdon** [comment]
получается что из 17 папок у нас в 7 из них нету контента. сейчас тогда сделаю

**Comment by atherdon** [comment]
@Olgalex 
файлы из основного репозитория

Q; https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD/tests/q/content.md
ul-list: https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/replacerMD/tests/lists-only/content.md
code: https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD/tests/code/content.md
del: https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD/tests/del/content.md

**Comment by atherdon** [comment]
link https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD/tests/link/complex-link/content.md
strong: https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD/tests/strong/content.md

**Comment by Olgalex** [comment]
Это там сейчас и размещено, что сделать нужно?

**Comment by atherdon** [comment]
> Это там сейчас и размещено, что сделать нужно?

нам нужно скопировать контент файлы из основного репозитория в этот репозиторий. иначе нам нечего будет тестировать 

сс @Olgalex

**Comment by atherdon** [comment]
@Olgalex can you go through all the folders inside `test` folder and review it again.

we should have only content.md and *.test.js files there.
i just opened the paragraph folder and this is what I find

![image](https://user-images.githubusercontent.com/1469198/178462041-353fdb98-fc9c-44cd-82ce-f1a9f52d3295.png)

**Comment by Olgalex** [comment]
do i delete some as paragraph.md?
