### ISSUE TITLE
comments to latest PR

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#170]
https://github.com/LLazyEmail/markdown-regex/pull/163

https://user-images.githubusercontent.com/1469198/180204707-6fde03a1-cc80-451d-9022-ab33baf61d67.mp4

**Comment by atherdon** [comment]
added #171

**Comment by Olgalex** [comment]
some files still without content, such as
br
em
empty-ol
empty-ul
paragraph
Also, please check if i was correct whith files, wich have long content text. Such as
header
image
link
ol-list
strong

**Comment by atherdon** [comment]
will take a look

**Comment by atherdon** [comment]
br located in #171

**Comment by atherdon** [comment]
em also have necessary data, #215

**Comment by atherdon** [comment]
**paragraph**, few paragraphs added

**Comment by atherdon** [comment]
we have few **headers** here: https://raw.githubusercontent.com/LLazyEmail/markdown-regex/main/tests/header/content.md
done.

**Comment by atherdon** [comment]
**images** get fixed
done

**Comment by atherdon** [comment]
**link** is fine

**Comment by atherdon** [comment]
**ol-list** is fine
**strong** is fine

@Olgalex im closing this task, but please do a sync of your version as i did some code changes.
Can you also take a look through all files and confirm here that all content.md files have necessary data inside?
