### ISSUE TITLE
migrate missing content

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#171]
- https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD-move-to-domain/tests/italic-first-sentence/italic.md
- https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD-move-to-domain/tests/br/br.md

**Comment by Olgalex** [comment]
where is italic.md?

**Comment by atherdon** [comment]
> * https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD-move-to-domain/tests/italic-first-sentence/italic.md

here it is: https://raw.githubusercontent.com/LLazyEmail/markdown-to-email/main/tests/replacerMD-move-to-domain/tests/italic-first-sentence/italic.md

**Comment by atherdon** [comment]
@Olgalex did we migrated italic aka em content file into our repository? if no, please submit a pr, I think it's related to #181

**Comment by atherdon** [comment]
@Olgalex can tell me status about this task

**Comment by Olgalex** [comment]
we did it, you can close
