### ISSUE TITLE
empty content file for em.test

### ISSUE THREAD

**Issue by Olgalex** [LLazyEmail/markdown-regex#181]
**Describe the bug**
expect(recieved).toBe(expected) !== object is equality

**To Reproduce**
Go to RegEx: `REGEXP_EM`

**Expected result**
expect(recieved).toBe(expected) === object is equality

**Actual result**
expect(recieved).toBe(expected) !== object is equality

**Additional context**
content.md is empty
https://github.com/LLazyEmail/markdown-regex/blob/main/tests/em/content.md

**Comment by atherdon** [comment]
i thinks it's a duplicate of #215, right? can i close this task

**Comment by Olgalex** [comment]
yes, you can close this task

**Comment by atherdon** [comment]
thank you, closing then
