### ISSUE TITLE
remove string from test scopes

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#86]
на видео я сказал что нам нужно убрать текст внутри строки - потому что пива у нас нету в тестах )))

**Comment by atherdon** [comment]
ты правда заменил, но все равно нужно убрать значение сейчас

**Comment by Bogdan060895** [comment]
Что именно нужно убрать ?

**Comment by atherdon** [comment]
Данные в строке нужно удалить

**Comment by Bogdan060895** [comment]
Удалил, надеюсь, верно. Мб, можешь посоветовать какой-то ресурс для изучения JS синтаксиса, для общего понимания?

**Comment by atherdon** [comment]
я нехочу сейчас давать много чего "учить". все дам со временем

**Comment by atherdon** [comment]
не, неправильно сделал

**Comment by Bogdan060895** [comment]
переделал еще раз

**Comment by atherdon** [comment]
окей, пойдет - хотя будет ошибка. но это решим в следующих задачах. закрываю
