### ISSUE TITLE
Task #2: add 3 empty "test" methods inside each block

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#87]
теперь мы добавим вторые блоки из примера

**Comment by atherdon** [comment]
@Bogdan060895 переименовал задачи. нужно начать с нее

**Comment by Bogdan060895** [comment]
Привет, освободился от своих задач, залез в таски, не совсем понял, какие блоки из какого примера нужно тут добавить.

**Comment by atherdon** [comment]
@Bogdan060895 а предыдущий таск был закончен? я просто не проверял код...

привет)

**Comment by atherdon** [comment]
вроде прошлые задачи были выполнены

**Comment by atherdon** [comment]
тут нужно добавить 3 пустых блока с tests внутрь describe

**Comment by atherdon** [comment]
первым параметром там нужно передавать пустую строку. 
тоже самое и с блоком describe.  а вторым параметром уже идет функция(сейчас первый параметр пропущен, а функция есть). посмотри как в том примере, только строку сделай пустой

https://github.com/Bogdan060895/markdown-regex-1/commit/75e165992934c0683d5d2f35b460506753272c8c#diff-b726e26821efad3b4800faf221c57010570fd00d11fe878a9be377de256f9263R3

**Comment by atherdon** [comment]
все остальное ок

**Comment by atherdon** [comment]
думаю можно ускорить наш процесс - попробую сегодня подготовить новые 10 тасков

**Comment by Bogdan060895** [comment]
Вроде, пофиксил все 17 файлов. Я правильно понимаю, что пустые строки должны быть перед describe и после, а между функциями test пустые строки не нужны?

**Comment by atherdon** [comment]
я имел ввиду что нужно 
```
describe('', () => ...)
и test('', () => ...)
```

**Comment by atherdon** [comment]
сделаете это и можете переходить к след задаче

**Comment by Bogdan060895** [comment]
сделал
