### ISSUE TITLE
Task4: добавить описание для первого блока тестов

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#89]
'should match the expected ...'

позже заменим троеточие

**Comment by Bogdan060895** [comment]
я так понял, описание - это то, что находится внутри функции describe ? 

describe('my beverage', () => {
  test('is delicious', () => {
  });
});

такого рода строка должны быть ?
test ( 'should match the expected ...' , () => {
});

**Comment by atherdon** [comment]
это 4я задача, сейчас переименую

**Comment by atherdon** [comment]
> я так понял, описание - это то, что находится внутри функции describe ?
да

> такого рода строка должны быть ? test ( 'should match the expected ...' , () => { });

да

но плз задачи делать попорядку

**Comment by Bogdan060895** [comment]
добавил описание во все файлы
