### ISSUE TITLE
Task#5: добавить в describe название нашей константы, которая хранить значение регулярного выражения.

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#90]
константу мы подключаем в первой строке, нужно чтобы в строке теперь она тоже была. так будет понятнее

**Comment by atherdon** [comment]
это продолжение таска №3

**Comment by Bogdan060895** [comment]
название константы - это то, что в фигурных скобках или то, что после равно идет ? правильно ли я сделал в таске 3?

**Comment by atherdon** [comment]
вроде правильно сделано. если что поправим в будущем
