### ISSUE TITLE
#6: нужно сделать sync проекта

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#95]
я добавил ваши изменения в основной репозиторий, но теперь вам нужно сделать sync своей клонированной версии, чтобы дерево с изменениями у нас было одинаковое.

![image](https://user-images.githubusercontent.com/1469198/170238693-797d1460-7674-478d-b5e5-92dd56ef5cea.png)

у вас в гитхабе должна быть кнопка для этого

**Comment by Bogdan060895** [comment]
а что нужно указать в title и  description ?

**Comment by Bogdan060895** [comment]
вроде, сделал

**Comment by atherdon** [comment]
пока еще нет

**Comment by Bogdan060895** [comment]
нужно какое-то время для обработки или я что-то не то сделал ? сейчас кнопка "open pull request" уже не доступна

**Comment by atherdon** [comment]
так сейчас все ваши изменения перенесены в основной репозиторий. поэтому и
не активна

---

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by atherdon** [comment]
![image](https://user-images.githubusercontent.com/1469198/170483433-949f1516-125d-4270-b3bc-7cbbf611e631.png)

**Comment by Bogdan060895** [comment]
что это значит ?)

**Comment by atherdon** [comment]
> что это значит ?)

это значит что ваш локальный репозиторий не синхронен досих пор. когда вы открываете pull request - вы отправляете изменения в мой репозиторий. при этом, когда я делаю изменения в основном репозитории, вы их себе не "забираете" и у нас получается разница между репозиториями. 

я сегодня добавил конфиг jest в основной репозиторий, и теперь критично становится то что у вас нет этих изменений. без них jest не запустится

**Comment by Bogdan060895** [comment]
а сейчас?

**Comment by atherdon** [comment]
теперь гуд.
таск закрываю, но добавлю потом еще изменений, чтобы закрепить sync

**Comment by atherdon** [comment]
добавил изменений, которые могут сделать конфликт между нашими версиями, нужен sync ))
