### ISSUE TITLE
#7 реорганизация файлов

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#96]
для каждого файла тестов создайте отдельную директорию(название такое же, только без `.js`)
перенесите эти файлы в соответствующие папки
и создайте в каждой папке файл content.md в котором напишите 
```
### testing content will be here
```

наша задачей будет вначале сделать простые кейсы, когда у нас строка внутри нашего файла будет сравниваться на предмет работы с regex который мы подключаем.

тоесть если наша задача - проверить и найти в файле все ссылки, вначале мы просто добавим ссылку в файл и проверим - запустится ли наш тест и вернет ли нам regex true(существует попадание) или false(отсутствует значение)

**Comment by Bogdan060895** [comment]
сделал

**Comment by atherdon** [comment]
круто что вы обновили путь к файлам
