### ISSUE TITLE
#8 перенос контента [длинный таск, будет обновлятся время от времени]

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#98]
мы прошли первый этап притирки и настройки работы, теперь начинается интересная часть.
congratulations!

сейчас мы потихоньку начнем переносить содержимое тестов, которые лежат в основном проекте.
и для этого нам нужны буду примеры контента, с помощью которого мы и будем проверять наши regexp`s

задача немного монотонная, когда закроем несколько таких задач - попробуем сделать и вызвать парочку простых тестов.

как именно вы его перенесете - дело ваше. просто скопировать в браузере может не получится

- [x] перенести этот [файл](https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/typography/br/content.md) в папку, отвечающую за работу с links
- [x] перенос [файла](https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/replacerMD/tests/paragraph/paragraph.md) в папку paragraph
- [x] перенос [файла](https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/replacerMD/tests/strong/content.md) в strong
- [x] move [file](https://github.com/LLazyEmail/markdown-to-email/tree/main/tests/replacerMD/tests/code) into code folder 
- [x] [file](https://github.com/LLazyEmail/markdown-to-email/tree/main/tests/replacerMD/tests/del) -> del folder
- [x] [file](https://github.com/LLazyEmail/markdown-to-email/tree/main/tests/replacerMD/tests/br) -> br folder
- [x] [file](https://github.com/LLazyEmail/markdown-to-email/blob/main/tests/replacerMD/tests/blockquote/content.md) -> blockquote folder

**Comment by atherdon** [comment]
когда в commit message вы указываете номер задачи( like `doing #98` ), ваши изменения могут быть видны на этой странице

**Comment by Bogdan060895** [comment]
Я изменил содержание файла content.md по первому пункту, но не уверен, что правильною Нужна проверка)

**Comment by atherdon** [comment]
смогу проверить завтра несколько задач, пока продолжайте без меня

**Comment by Bogdan060895** [comment]
Все сделал, вроде. Вопрос только по последнему пункту, там нужно было изменить содержание только файла content.md или и перенести файл index.test.js тоже ?

**Comment by Bogdan060895** [comment]
вроде, готово

**Comment by atherdon** [comment]
Сижу без света, посмотрю позже

**Comment by atherdon** [comment]
@Bogdan060895 вроде все гуд. принимаю пулл-реквест

**Comment by Bogdan060895** [comment]
гуд, ожидаю тогда

**Comment by atherdon** [comment]
> гуд, ожидаю тогда

добавил других тасков, позже добавлю еще пунктов в этот

**Comment by atherdon** [comment]
@Bogdan060895 давайте вместе пройдемся по файлам content* и посмотрим какие не были перенесены?

я заметил что для
- q
- ulList

контент не был перенесен

**Comment by Bogdan060895** [comment]
а где взять содержимое для этих файлов ?

**Comment by Bogdan060895** [comment]
вижу, что контент есть только в паре файлов content.

**Comment by atherdon** [comment]
Перечислите в каких файлах стоит наша первая заглушка и от этого будем
двигаться вперед

вс, 5 июн. 2022 г., 7:34 PM Bogdan060895 ***@***.***>:

**Comment by atherdon** [comment]
Контент для тестов мы будем брать из репозитория markdown to email, как мы
делали в прошлый раз с вами

вс, 5 июн. 2022 г., 10:12 PM Arthur Tkachenko <
***@***.***>:
