### ISSUE TITLE
basic true/false test for matching simple string with a regex

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-regex#99]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

**Comment by atherdon** [comment]
```
const regex = /foo/g; // the "global" flag is set

// regex.lastIndex is at 0
regex.test('foo')     // true
```

**Comment by Bogdan060895** [comment]
Прочитал статью по ссылке. Не могу сказать, что все понял, но ознакомился)

**Comment by atherdon** [comment]
я пока этот таск на вас не перекидывал. ну думаю сделаем этот тест как базовый для проверки для всех regexp

**Comment by atherdon** [comment]
скоро начнем выполнять эту задачу, в #116 мы посути начинаем выполнения этой задачи. выглядеть будет немного коряво, но я пока не придумал как сделать красивее
